[package]
name = "embedded-packet-io"
version = "0.1.0"
edition = "2024"
description = "Embedded packet IO"
license = "CC0-1.0"

[dependencies]
embedded-io = { version = "0.6.1", default-features = false }
embedded-io-async = { version = "0.6.1", default-features = false }
heapless = "0.8.0"
